### ISSUE TITLE
SIGINT and SIGTERM handlers

### ISSUE THREAD

**Issue by aryehklempner** [aryehklempner/tesla#2]
Any self-respecting, non-trivial interactive process needs one. (Well, you know what I mean.)

**Comment by aryehklempner** [comment]
Also SIGHUP.

**Comment by aryehklempner** [comment]
And SIGQUIT.

**Comment by aryehklempner** [comment]
Freeciv requires two SIGTERM [^C] in one second to close. It's worth implementing that later.

**Comment by arayaynonsecure** [comment]
*SIGINT ^^

**Comment by arayaynonsecure** [comment]
This behavior should also be implemented for SIGQUIT and SIGTSTP to avoid accidents.
